spring:
  datasource:
    url: jdbc:postgresql://ep-frosty-fire-awvd905m-pooler.c-12.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_YTpoa0zi9VRx
  jpa:
    hibernate:
      ddl-auto: update

cloudinary:
  cloud-name: dei5cvfef
  api-key: 973133641513743
  api-secret: 9fjyJmJMOzYofDaBkwuGexvqysA
