ALTER TABLE courses ADD COLUMN IF NOT EXISTS payment_type VARCHAR(20) DEFAULT 'FULL_PAYMENT';
ALTER TABLE courses ADD COLUMN IF NOT EXISTS down_payment DOUBLE PRECISION;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS installment_amount DOUBLE PRECISION;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS installment_frequency VARCHAR(50);
ALTER TABLE courses ADD COLUMN IF NOT EXISTS number_of_installments INTEGER;
